function [Freq, IC1real, IC1imag, IC2real, IC2imag, IC3real, IC3imag, IC4real, IC4imag] = capacitorStepResponse(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [FREQ, IC1REAL, IC1IMAG, IC2REAL, IC2IMAG, IC3REAL, IC3IMAG, IC4REAL,
%  IC4IMAG] = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  [FREQ, IC1REAL, IC1IMAG, IC2REAL, IC2IMAG, IC3REAL, IC3IMAG, IC4REAL,
%  IC4IMAG] = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [Freq, IC1real, IC1imag, IC2real, IC2imag, IC3real, IC3imag, IC4real, IC4imag] = importfile("C:\Github\KTH\DC-Bus Current Modelling\Matlab\PhAResponse.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Nov-2024 11:20:19

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Freq", "IC1real", "IC1imag", "IC2real", "IC2imag", "IC3real", "IC3imag", "IC4real", "IC4imag"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Freq", "IC1real", "IC1imag", "IC2real", "IC2imag", "IC3real", "IC3imag", "IC4real", "IC4imag"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Freq = tbl.Freq;
IC1real = tbl.IC1real;
IC1imag = tbl.IC1imag;
IC2real = tbl.IC2real;
IC2imag = tbl.IC2imag;
IC3real = tbl.IC3real;
IC3imag = tbl.IC3imag;
IC4real = tbl.IC4real;
IC4imag = tbl.IC4imag;

end