%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Github\KTH\DC-Bus Current Modelling\PhCResponse.txt
%
% Auto-generated by MATLAB on 15-Nov-2024 11:52:35
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Freq", "IC1_Re", "IC1_Im", "IC2_Re", "IC2_Im", "IC3_Re", "IC3__Im", "IC4__Re", "IC4_Im"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Freq", "IC1_Re", "IC1_Im", "IC2_Re", "IC2_Im", "IC3_Re", "IC3__Im", "IC4__Re", "IC4_Im"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Github\KTH\DC-Bus Current Modelling\PhCResponse.txt", opts);

%% Convert to output type
Freq = tbl.Freq;
IC1_Re = tbl.IC1_Re;
IC1_Im = tbl.IC1_Im;
IC2_Re = tbl.IC2_Re;
IC2_Im = tbl.IC2_Im;
IC3_Re = tbl.IC3_Re;
IC3__Im = tbl.IC3__Im;
IC4__Re = tbl.IC4__Re;
IC4_Im = tbl.IC4_Im;

%% Clear temporary variables
clear opts tbl