function [Ch1, Ch2, Ch3] = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  [CH1, CH2, CH3] = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as column vectors.
%
%  [CH1, CH2, CH3] = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  [CH1, CH2, CH3] = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Ch1, Ch2, Ch3] = importfile("C:\Users\enesa\KTH\Shahriar Sarmast Ghahfarokhi - topology\DPT_Results\Test-Oct-31-23 Time 16 11 32--V 500-t1 4-t2 10-t3 4-td 10-tdead 200ns.xlsx", "sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Oct-2023 16:49:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Ch1", "Ch2", "Ch3"];
opts.SelectedVariableNames = ["Ch1", "Ch2", "Ch3"];
opts.VariableTypes = ["char", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
Ch1 = tbl.Ch1;
Ch2 = tbl.Ch2;
Ch3 = tbl.Ch3;
end