"""
Temperature maps from the Icepak grid exports (simulation/bb_icepak/results/grid_*.fld), with the component outlines.

    python scripts/plot_icepak.py
    -> reports/design-report-v2/figures/thermal_maps.pdf|png, thermal_numbers.tex
"""
import os
import sys

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import Rectangle  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "simulation", "bb_icepak", "results")
OUT = os.path.join(ROOT, "reports", "design-report-v2")
sys.path.insert(0, os.path.join(ROOT, "simulation", "bb_q3d"))
import bb_geometry as geo  # noqa: E402

plt.rcParams.update({"font.size": 8})
G = geo.build()
P, Y = G["params"], G["rows"]
yqh, yql = sum(Y["qhd"]) / 2 + 1.0, sum(Y["qld"]) / 2 + 1.0


def load(path):
    d = np.loadtxt(path, skiprows=2)
    x, y, t = d[:, 0] * 1e3, d[:, 1] * 1e3, d[:, 3]
    xs, ys = np.unique(np.round(x, 4)), np.unique(np.round(y, 4))
    T = np.full((len(ys), len(xs)), np.nan)
    ix = np.searchsorted(xs, np.round(x, 4))
    iy = np.searchsorted(ys, np.round(y, 4))
    T[iy, ix] = t
    return xs, ys, T


def outlines(ax):
    kw = dict(fill=False, lw=0.6, ec="k")
    for s in (-1, 1):
        for yc in (yqh, yql):
            ax.add_patch(Rectangle((s * P["xc"] - 2.5, yc - 1.5), 5, 3, **kw))
        for i in range(6):
            x = s * P["xc"] + (i - 2.5) * P["cap_p"]
            ax.add_patch(Rectangle((x - 0.625, Y["capn"][0]), 1.25, Y["capp"][1] - Y["capn"][0], fill=False, lw=0.3, ec="0.3"))
        for g0 in (Y["p1"][1], Y["n1"][1], Y["p2"][1]):
            gc = g0 + P["gap"] / 2
            for xb in P["bank_x"]:
                ax.add_patch(Rectangle((s * xb - 1.25, gc - 1.6), 2.5, 3.2, fill=False, lw=0.3, ec="0.3"))
    ax.add_patch(Rectangle((-1, Y["ac"][0] + 0.6), 2, 2, **kw))


cases = [("", "top cold plate only")]
if os.path.exists(os.path.join(RES, "grid_board_both.fld")):
    cases.append(("_both", "top + bottom cold plate"))
fig, axes = plt.subplots(len(cases), 2, figsize=(7.2, 3.3 * len(cases)), squeeze=False)
mac = {}
vmax = {}
for tag in ("devices", "board"):
    vmax[tag] = max(np.nanmax(load(os.path.join(RES, "grid_%s%s.fld" % (tag, s)))[2]) for s, _ in cases)
for r, (suf, lab) in enumerate(cases):
    for c, (tag, title) in enumerate((("devices", "device layer (z = 2.0 mm)"), ("board", "board mid-plane (z = 0.8 mm)"))):
        xs, ys, T = load(os.path.join(RES, "grid_%s%s.fld" % (tag, suf)))
        ax = axes[r][c]
        im = ax.imshow(T, origin="lower", extent=(xs[0], xs[-1], ys[0], ys[-1]), cmap="inferno", vmin=60,
                       vmax=vmax[tag], aspect="equal")
        outlines(ax)
        ax.invert_yaxis()                          # same orientation as the layout drawings (DC terminals on top)
        ax.set_title("%s, %s" % (lab, title), fontsize=7.5)
        ax.set_xlabel("x [mm]")
        if c == 0:
            ax.set_ylabel("y [mm]")
        cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
        cb.set_label("T [$^\\circ$C]")
        mac["Th%s%s" % (tag.capitalize(), "Both" if suf else "Top")] = "%.0f" % np.nanmax(T)
fig.tight_layout()
fig.savefig(os.path.join(OUT, "figures", "thermal_maps.pdf"))
fig.savefig(os.path.join(OUT, "figures", "thermal_maps.png"), dpi=170)


def results(suf):
    f = os.path.join(RES, "icepak_results%s.txt" % suf)
    if not os.path.exists(f):
        return {}
    out = {}
    for line in open(f):
        p = line.split()
        try:
            out[p[0]] = float(p[1].strip("[]',"))
        except (ValueError, IndexError):
            pass
    return out


for suf, key in (("", "Top"), ("_both", "Both")):
    r = results(suf)
    if r:
        mac["ThFet" + key] = "%.0f" % max(r[k] for k in ("QH_L", "QL_L", "QH_R", "QL_R"))
        mac["ThPcb" + key] = "%.0f" % r["PCB"]
        mac["ThCap" + key] = "%.0f" % max(r.get("C1210_1_R0", 0), r.get("C1210_3_R0", 0))
        mac["ThDrv" + key] = "%.0f" % r["Driver"]
with open(os.path.join(OUT, "thermal_numbers.tex"), "w") as f:
    f.write("% generated by scripts/plot_icepak.py\n")
    for k, v in mac.items():
        f.write("\\newcommand{\\%s}{%s}\n" % (k, v))
print(mac)
