"""
Post-processing of BB_BUS (bb_q3d_busbar.py): loop inductance and resistance of the laminated busbar.
Loop vectors (branch currents, source terminal -> net sink): current enters the cell at TAB_P, flows in DC+ to the
DC+ terminal of leg k and returns from its DC- terminal in DC- to TAB_N; leg-to-leg loops between two legs.

    python simulation/bb_q3d/busbar_post.py -> results/busbar_summary.json, reports/pcb-fab/busbar_numbers.tex
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")


def block(lines, title):
    for i, l in enumerate(lines):
        if l.strip() == title:
            names = lines[i + 1].split()
            rows = [r.split() for r in lines[i + 2:i + 2 + len(names)]]
            return names, np.array([[float(v) for v in r[1:]] for r in rows])
    raise KeyError(title)


lines = open(os.path.join(RES, "BB_BUS_matrix.txt")).read().splitlines()
out = {}
for tag, lt, rt in (("ac", "AC Inductance Matrix", "AC Resistance Matrix"), ("dc", "DC Inductance Matrix", "DC Resistance Matrix")):
    names, L = block(lines, lt)
    _, R = block(lines, rt)
    idx = {n: k for k, n in enumerate(names)}

    def v(d):
        x = np.zeros(len(names))
        for k, s in d.items():
            x[idx[k]] = s
        return x

    res = {}
    for leg in "ABC":
        p = v({"DCP:J1_" + leg: -1, "DCN:J2_" + leg: 1})
        res["L_tab_to_leg_%s_nH" % leg] = float(p @ L @ p)
        res["R_tab_to_leg_%s_mOhm" % leg] = float(p @ R @ p) * 1e3
    for a, b in (("A", "B"), ("B", "C"), ("A", "C")):
        p = v({"DCP:J1_" + a: 1, "DCP:J1_" + b: -1, "DCN:J2_" + a: -1, "DCN:J2_" + b: 1})
        res["L_leg_%s%s_nH" % (a, b)] = float(p @ L @ p)
        res["R_leg_%s%s_mOhm" % (a, b)] = float(p @ R @ p) * 1e3
    out[tag] = res
json.dump(out, open(os.path.join(RES, "busbar_summary.json"), "w"), indent=1)
os.makedirs(os.path.join(HERE, "..", "..", "reports", "pcb-fab"), exist_ok=True)
with open(os.path.join(HERE, "..", "..", "reports", "pcb-fab", "busbar_numbers.tex"), "w") as f:
    f.write("% generated by simulation/bb_q3d/busbar_post.py (1 MHz AC, DC)\n")
    w = {"A": "One", "B": "Two", "C": "Three"}
    for tag in ("ac", "dc"):
        T = "Ac" if tag == "ac" else "Dc"
        for leg in "ABC":
            f.write("\\newcommand{\\BusL%sLeg%s}{%.2f}\n" % (T, w[leg], out[tag]["L_tab_to_leg_%s_nH" % leg]))
            f.write("\\newcommand{\\BusR%sLeg%s}{%.3f}\n" % (T, w[leg], out[tag]["R_tab_to_leg_%s_mOhm" % leg]))
        f.write("\\newcommand{\\BusL%sAB}{%.2f}\n" % (T, out[tag]["L_leg_AB_nH"]))
        f.write("\\newcommand{\\BusL%sAC}{%.2f}\n" % (T, out[tag]["L_leg_AC_nH"]))
        f.write("\\newcommand{\\BusR%sAB}{%.3f}\n" % (T, out[tag]["R_leg_AB_mOhm"]))
print(json.dumps(out, indent=1))
