"""
Post-processing of BB_CS / BB_CS_noK (bb_q3d_cs.py): loop and mutual inductances from the 100 MHz AC inductance
matrix of the Q3D terminal branches (each branch: source terminal -> net sink).

A loop is a vector of branch currents: +1 where the loop current enters a net at a source terminal, -1 where it
leaves. L_loop = p' L p, L_gate = g' L g, common-source inductance L_CS = g' L p (mutual between gate and power loop).

    python simulation/bb_q3d/cs_post.py  -> results/cs_summary.json, prints a table
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")


def block(lines, title):
    for i, l in enumerate(lines):
        if l.strip() == title:
            names = lines[i + 1].split()
            rows = [r.split() for r in lines[i + 2:i + 2 + len(names)]]
            return names, np.array([[float(v) for v in r[1:]] for r in rows])
    raise KeyError(title)


def analyse(tag):
    lines = open(os.path.join(RES, tag + "_matrix.txt")).read().splitlines()
    names, L = block(lines, "AC Inductance Matrix")
    _, R = block(lines, "AC Resistance Matrix")
    idx = {n: k for k, n in enumerate(names)}

    def vec(d):
        v = np.zeros(len(names))
        for k, s in d.items():
            v[idx[k]] = s
        return v

    out = {}
    for side, other in (("L", "R"), ("R", "L")):
        p_loc = vec({"DCP:CapP" + side: 1, "DCP:QH_D_" + side: -1, "AC:QH_S_" + side: 1, "AC:QL_D_" + side: -1,
                     "DCN:QL_S_" + side: 1, "DCN:CapN" + side: -1})
        g = vec({"G:Gate_" + side: -1, "DCN:QL_S_" + side: 1, "DCN:DrvGnd": -1})
        p_oth = vec({"DCP:CapP" + other: 1, "DCP:QH_D_" + other: -1, "AC:QH_S_" + other: 1, "AC:QL_D_" + other: -1,
                     "DCN:QL_S_" + other: 1, "DCN:CapN" + other: -1})
        g_oth = vec({"G:Gate_" + other: -1, "DCN:QL_S_" + other: 1, "DCN:DrvGnd": -1})
        # source-side (low-side) part of the power loop only: current from the QL source to the local caps
        p_src = vec({"DCN:QL_S_" + side: 1, "DCN:CapN" + side: -1})
        out[side] = dict(L_loop_local_nH=float(p_loc @ L @ p_loc), L_gate_nH=float(g @ L @ g),
                         L_CS_nH=float(g @ L @ p_loc), L_CS_srcpath_nH=float(g @ L @ p_src),
                         M_gate_otherloop_nH=float(g @ L @ p_oth), M_gate_gate_nH=float(g @ L @ g_oth),
                         R_gate_100MHz_mOhm=float(g @ R @ g) * 1e3)
    return out


res = {}
for tag in ("BB_CS", "BB_CS_noK"):
    if os.path.exists(os.path.join(RES, tag + "_matrix.txt")):
        res[tag] = analyse(tag)
json.dump(res, open(os.path.join(RES, "cs_summary.json"), "w"), indent=1)
for tag, r in res.items():
    print(tag)
    for side, v in r.items():
        print("  %s " % side + "  ".join("%s=%.3f" % kv for kv in v.items()))


# LaTeX macros for the paper
mac = {}
if "BB_CS" in res:
    k = res["BB_CS"]
    mac.update(LcsKel="%.3f" % (0.5 * (k["L"]["L_CS_nH"] + k["R"]["L_CS_nH"])),
               LgateCs="%.2f" % (0.5 * (k["L"]["L_gate_nH"] + k["R"]["L_gate_nH"])),
               MgateOther="%.3f" % abs(k["L"]["M_gate_otherloop_nH"]),
               MgateGate="%.2f" % k["L"]["M_gate_gate_nH"])
if "BB_CS_noK" in res:
    k = res["BB_CS_noK"]
    mac.update(LcsNoK="%.3f" % (0.5 * (k["L"]["L_CS_nH"] + k["R"]["L_CS_nH"])),
               LgateNoK="%.2f" % (0.5 * (k["L"]["L_gate_nH"] + k["R"]["L_gate_nH"])))
with open(os.path.join(HERE, "..", "..", "reports", "paper", "cs_numbers.tex"), "w") as f:
    f.write("% generated by simulation/bb_q3d/cs_post.py\n")
    for a, b in mac.items():
        f.write("\\newcommand{\\%s}{%s}\n" % (a, b))
print(mac)
