# SPB cell assembly for Autodesk Fusion (Utilities > Scripts and Add-Ins > Scripts > "+" > this folder > Run).
#
# One SPB cell (submodule): three leg boards (KiCad STEP export, ../../spb-building-block/spb-building-block.step)
# under one long liquid cold plate, laminated DC busbar on the bottom side, phase leads, cell aux/control board.
# All dimensions in mm (converted to Fusion's internal cm). Coordinates: x axial, y circumferential (board y of the
# STEP), z radial outward; board bottom at z = 0, components and cold plate at z > 0, busbar and housing at z < 0.
#
# Generated by the KTH PCB-Design repo; geometry follows scripts/make_kicad_bb.py. Concept level, not a drawing for
# manufacture: channel layout, pedestal heights, busbar thicknesses and creepage distances are design parameters.

import os
import traceback

import adsk.core
import adsk.fusion

HERE = os.path.dirname(os.path.abspath(__file__))
STEP = os.path.normpath(os.path.join(HERE, "..", "..", "spb-building-block", "spb-building-block.step"))

# ------------------------------------------------------------------ parameters (mm)
P = dict(
    n_legs=3, pitch=36.0,                       # leg boards along x: 33 mm board + 3 mm gap
    bx0=-16.5, bx1=16.5, by0=-27.8, by1=24.9, bt=1.6,   # leg board outline in the STEP frame
    # components missing in the STEP (VRML-only envelopes): EPC2361 3 x 5 mm, 2EDF7275K 5 x 5 mm
    fet_h=0.65, drv_h=1.0, cap_bank_h=2.5,
    # cold plate
    plate_z0=6.0, plate_t=8.0, plate_x0=-20.0, plate_x1=118.0, plate_y0=-27.0, plate_y1=24.0,
    ch_w=8.0, ch_h=3.0, ch_z0=8.0, ch_y=(-7.0, 6.5),            # U-channel: pass under the FETs, return under the bank
    tim_t=0.3, aln_t=0.63,
    # laminated busbar (under the DC terminal zone)
    term_dc_h=6.5, term_ac_h=3.5,              # REDCUBE 74650174 / 74650094 body heights below the board
    bb_cu=1.5, bb_ins=0.25, bb_y0=11.8, bb_y1=25.8, bb_x0=-24.0, bb_x1=96.0,
    clr_hole=9.0, boss_d=7.0, scr_d=4.0, head_d=7.0, head_h=2.8,
    # phase leads: 8 x 2 mm copper bars, stepped in depth so they pass under the other legs
    lead_w=8.0, lead_t=2.0, lead_z=(-6.0, -9.5, -13.0), lead_x_end=135.0, lead_lane_y=-12.0, ffc_lane_y=-17.0,
    # aux board
    aux_x0=91.5, aux_x1=115.5, aux_y0=-24.0, aux_y1=20.0,
    # housing segment and insulation
    ins_t=0.5, housing_z1=-17.0, housing_t=6.0,
)
# feature positions on one leg board (STEP frame, mm): from make_kicad_bb.py with y -> -y
FETS = [(-7.5, -4.9), (-7.5, -9.2), (7.5, -4.9), (7.5, -9.2)]
DRIVER = (0.0, -7.0)
J1, J2, J3, J4 = (-6.0, 18.8), (6.0, 18.8), (-5.9, -21.5), (8.6, -19.5)
HOLES = [(-14.1, -25.4), (14.1, -25.4), (-14.1, 22.4), (14.1, 22.4)]
PED_FET = [(-10.25, -4.75, -10.9, -3.2), (4.75, 10.25, -10.9, -3.2)]           # x0, x1, y0, y1 over QH+QL of a cell
PED_BANK = [(-15.0, -3.5, 1.1, 12.3), (3.5, 15.0, 1.1, 12.3)]                   # over the 1210 bank rows

app = adsk.core.Application.get()
ui = app.userInterface
TB = adsk.fusion.TemporaryBRepManager.get()


def cm(v):
    return v / 10.0


def pt(x, y, z):
    return adsk.core.Point3D.create(cm(x), cm(y), cm(z))


def tbox(x0, x1, y0, y1, z0, z1):
    c = pt((x0 + x1) / 2, (y0 + y1) / 2, (z0 + z1) / 2)
    obb = adsk.core.OrientedBoundingBox3D.create(c, adsk.core.Vector3D.create(1, 0, 0), adsk.core.Vector3D.create(0, 1, 0),
                                                 cm(abs(x1 - x0)), cm(abs(y1 - y0)), cm(abs(z1 - z0)))
    return TB.createBox(obb)


def tcyl(x, y, z0, z1, d, axis="z"):
    if axis == "z":
        return TB.createCylinderOrCone(pt(x, y, z0), cm(d / 2), pt(x, y, z1), cm(d / 2))
    return TB.createCylinderOrCone(pt(z0, y, x), cm(d / 2), pt(z1, y, x), cm(d / 2))   # along x: x = z0..z1, (y, z=x)


def cut(body, tool):
    TB.booleanOperation(body, tool, adsk.fusion.BooleanTypes.DifferenceBooleanType)
    return body


def union(body, tool):
    TB.booleanOperation(body, tool, adsk.fusion.BooleanTypes.UnionBooleanType)
    return body


APPEAR = {}


def appearance(names):
    key = names[0]
    if key in APPEAR:
        return APPEAR[key]
    found = None
    for libname in ("Fusion Appearance Library", "Fusion 360 Appearance Library"):
        try:
            lib = app.materialLibraries.itemByName(libname)
        except Exception:
            lib = None
        if not lib:
            continue
        for n in names:
            a = lib.appearances.itemByName(n)
            if a:
                found = a
                break
        if found:
            break
    APPEAR[key] = found
    return found


AL = ["Aluminum - Satin", "Aluminum - Brushed", "Aluminum - Polished"]
CU = ["Copper - Satin", "Copper", "Copper - Polished"]
CER = ["Ceramic - Glossy (White)", "Ceramic - Matte (White)", "Plastic - Matte (White)"]
INS = ["Plastic - Matte (Yellow)", "Plastic - Glossy (Yellow)", "Paint - Enamel Glossy (Yellow)"]
DARK = ["Plastic - Matte (Black)", "Plastic - Glossy (Black)", "Paint - Enamel Glossy (Black)"]
BLUE = ["Plastic - Matte (Blue)", "Plastic - Glossy (Blue)", "Paint - Enamel Glossy (Blue)"]
GREEN = ["Plastic - Matte (Green)", "Plastic - Glossy (Green)", "Paint - Enamel Glossy (Green)"]
GREY = ["Paint - Enamel Glossy (Grey)", "Plastic - Matte (Gray)", "Steel - Satin"]
PEEK = ["Plastic - Matte (Beige)", "Plastic - Matte (White)", "Plastic - Glossy (White)"]


def new_comp(parent, name, x=0.0, y=0.0, z=0.0):
    m = adsk.core.Matrix3D.create()
    m.translation = adsk.core.Vector3D.create(cm(x), cm(y), cm(z))
    occ = parent.occurrences.addNewComponent(m)
    occ.component.name = name
    return occ.component


def add(comp, tbody, name, appear=None, opacity=None):
    b = comp.bRepBodies.add(tbody)
    b.name = name
    a = appearance(appear) if appear else None
    if a:
        b.appearance = a
    if opacity is not None:
        try:
            b.opacity = opacity
        except Exception:
            pass
    return b


def build(root):
    n, pitch = P["n_legs"], P["pitch"]
    xs = [k * pitch for k in range(n)]

    # ---------------- leg boards: STEP import once, then copies
    legs = new_comp(root, "Leg boards")
    if os.path.exists(STEP):
        leg0 = new_comp(legs, "Leg A")
        app.importManager.importToTarget(app.importManager.createSTEPImportOptions(STEP), leg0)
        for k in range(1, n):
            m = adsk.core.Matrix3D.create()
            m.translation = adsk.core.Vector3D.create(cm(xs[k]), 0, 0)
            occ = legs.occurrences.addExistingComponent(leg0, m)
            occ.component.name = "Leg A"          # same component, instances B, C
    else:
        ui.messageBox("STEP not found:\n%s\nUsing plain board blocks." % STEP)
        for k in range(n):
            c = new_comp(legs, "Leg %s" % "ABC"[k])
            add(c, tbox(xs[k] + P["bx0"], xs[k] + P["bx1"], P["by0"], P["by1"], 0, P["bt"]), "PCB", GREEN)
    # parts that are VRML-only in KiCad (not in the STEP): EPC2361 and 2EDF7275K as boxes
    parts = new_comp(root, "Transistors and drivers (envelopes)")
    for k in range(n):
        for (fx, fy) in FETS:
            add(parts, tbox(xs[k] + fx - 2.5, xs[k] + fx + 2.5, fy - 1.5, fy + 1.5, P["bt"], P["bt"] + P["fet_h"]),
                "EPC2361 %s" % "ABC"[k], DARK)
        add(parts, tbox(xs[k] + DRIVER[0] - 2.5, xs[k] + DRIVER[0] + 2.5, DRIVER[1] - 2.5, DRIVER[1] + 2.5, P["bt"],
                        P["bt"] + P["drv_h"]), "2EDF7275K %s" % "ABC"[k], DARK)

    # ---------------- cold plate with U-channel, pedestals, AlN tiles and TIM pads
    cp = new_comp(root, "Cold plate (liquid, grounded)")
    z0, z1 = P["plate_z0"], P["plate_z0"] + P["plate_t"]
    plate = tbox(P["plate_x0"], P["plate_x1"], P["plate_y0"], P["plate_y1"], z0, z1)
    cz0, cz1 = P["ch_z0"], P["ch_z0"] + P["ch_h"]
    w = P["ch_w"]
    ya, yb = P["ch_y"]
    xa, xb = P["plate_x0"] - 1.0, P["plate_x1"] - 8.0
    chan = tbox(xa, xb + w / 2, ya - w / 2, ya + w / 2, cz0, cz1)
    union(chan, tbox(xa, xb + w / 2, yb - w / 2, yb + w / 2, cz0, cz1))
    union(chan, tbox(xb - w / 2, xb + w / 2, ya - w / 2, yb + w / 2, cz0, cz1))
    cut(plate, chan)
    tim_top = {}
    for k in range(n):
        for tag, peds, h_part in (("FET", PED_FET, P["fet_h"]), ("bank", PED_BANK, P["cap_bank_h"])):
            for (px0, px1, py0, py1) in peds:
                zc = P["bt"] + h_part                            # contact surface (part top)
                za = zc + P["tim_t"]
                zal = za + P["aln_t"]
                union(plate, tbox(xs[k] + px0, xs[k] + px1, py0, py1, zal, z0 + 0.01))      # Al pedestal
                add(cp, tbox(xs[k] + px0, xs[k] + px1, py0, py1, za, zal), "AlN %s %s" % (tag, "ABC"[k]), CER)
                add(cp, tbox(xs[k] + px0 + 0.2, xs[k] + px1 - 0.2, py0 + 0.2, py1 - 0.2, zc, za),
                    "TIM %s %s" % (tag, "ABC"[k]), BLUE)
    # blind M2.5 holes for the insulated standoffs
    for k in range(n):
        for (hx, hy) in HOLES:
            cut(plate, tcyl(xs[k] + hx, hy, z0 - 0.1, z0 + 5.0, 2.1))
    add(cp, plate, "Cold plate", AL, 0.55)
    for yy, lab in ((ya, "inlet"), (yb, "outlet")):
        f = TB.createCylinderOrCone(pt(P["plate_x0"] - 14.0, yy, (cz0 + cz1) / 2), cm(4.0),
                                    pt(P["plate_x0"] + 0.5, yy, (cz0 + cz1) / 2), cm(4.0))
        cut(f, TB.createCylinderOrCone(pt(P["plate_x0"] - 14.5, yy, (cz0 + cz1) / 2), cm(2.5),
                                       pt(P["plate_x0"] + 1.0, yy, (cz0 + cz1) / 2), cm(2.5)))
        add(cp, f, "Coolant %s" % lab, AL)

    # ---------------- insulated standoffs (PEEK) between board top and plate
    so = new_comp(root, "Insulated standoffs (PEEK)")
    for k in range(n):
        for (hx, hy) in HOLES:
            s = tcyl(xs[k] + hx, hy, P["bt"], z0, 5.0)
            cut(s, tcyl(xs[k] + hx, hy, P["bt"] - 0.1, z0 + 0.1, 2.7))
            add(so, s, "Standoff", PEEK)
            add(so, tcyl(xs[k] + hx, hy, -2.0, z0 + 4.0, 2.5), "PEEK screw M2.5", PEEK)

    # ---------------- laminated DC busbar (DC+ at the terminals, DC- below, insulation between)
    bb = new_comp(root, "Laminated DC busbar")
    zt = -P["term_dc_h"]                                   # terminal faces
    zp0, zp1 = zt - P["bb_cu"], zt                         # DC+ copper
    zi0, zi1 = zp0 - P["bb_ins"], zp0                      # insulation
    zn0, zn1 = zi0 - P["bb_cu"], zi0                       # DC- copper
    y0, y1 = P["bb_y0"], P["bb_y1"]
    dcp = tbox(P["bb_x0"], P["bb_x1"] - 12.0, y0, y1, zp0, zp1)
    union(dcp, tbox(P["bb_x0"] - 14.0, P["bb_x0"] + 0.5, y0, y1, zp0, zp1))       # series tab to SM k-1
    dcn = tbox(P["bb_x0"] + 12.0, P["bb_x1"], y0, y1, zn0, zn1)
    union(dcn, tbox(P["bb_x1"] - 0.5, P["bb_x1"] + 14.0, y0, y1, zn0, zn1))       # series tab to SM k+1
    ins = tbox(P["bb_x0"] + 0.0, P["bb_x1"] + 2.0, y0 - 1.5, y1 + 1.5, zi0, zi1)
    for k in range(n):
        x1, x2 = xs[k] + J1[0], xs[k] + J2[0]
        cut(dcp, tcyl(x2, J2[1], zp0 - 0.1, zp1 + 0.1, P["clr_hole"]))           # clearance for the DC- boss
        cut(dcp, tcyl(x1, J1[1], zp0 - 0.1, zp1 + 0.1, P["scr_d"] + 0.4))
        cut(ins, tcyl(x2, J2[1], zi0 - 0.1, zi1 + 0.1, P["boss_d"] + 2.0))
        cut(ins, tcyl(x1, J1[1], zi0 - 0.1, zi1 + 0.1, P["head_d"] + 3.0))
        cut(dcn, tcyl(x1, J1[1], zn0 - 0.1, zn1 + 0.1, P["head_d"] + 3.0))       # access to the DC+ screw head
        union(dcn, tcyl(x2, J2[1], zn1 - 0.01, zt, P["boss_d"]))                 # boss up to the DC- terminal
        cut(dcn, tcyl(x2, J2[1], zn0 - 0.1, zt + 0.1, P["scr_d"] + 0.4))
        add(bb, tcyl(x1, J1[1], zp0 - P["head_h"], zt + 5.0, P["scr_d"]), "M4 screw DC+ %s" % "ABC"[k], GREY)
        add(bb, tcyl(x1, J1[1], zp0 - P["head_h"], zp0, P["head_d"]), "M4 head DC+ %s" % "ABC"[k], GREY)
        add(bb, tcyl(x2, J2[1], zn0 - P["head_h"], zt + 5.0, P["scr_d"]), "M4 screw DC- %s" % "ABC"[k], GREY)
        add(bb, tcyl(x2, J2[1], zn0 - P["head_h"], zn0, P["head_d"]), "M4 head DC- %s" % "ABC"[k], GREY)
    for xx, zz in ((P["bb_x0"] - 8.0, zp0), (P["bb_x1"] + 8.0, zn0)):
        cut(dcp if zz == zp0 else dcn, tcyl(xx, (y0 + y1) / 2, zz - 0.1, zz + P["bb_cu"] + 0.1, 5.3))
    add(bb, dcp, "DC+ plate", CU)
    add(bb, dcn, "DC- plate", CU)
    add(bb, ins, "Insulation film", INS, 0.8)

    # ---------------- phase leads (copper bars to the end winding)
    pl = new_comp(root, "Phase leads")
    for k in range(n):
        x3, y3 = xs[k] + J3[0], J3[1]
        zl = P["lead_z"][k]
        t, wl = P["lead_t"], P["lead_w"]
        yl = P["lead_lane_y"]
        bar = tbox(x3 - wl / 2, x3 + wl / 2, y3 - wl / 2, y3 + wl / 2, zl - t, -P["term_ac_h"])    # riser
        union(bar, tbox(x3 - wl / 2, x3 + wl / 2, y3 - wl / 2, yl + wl / 2, zl - t, zl))           # jog to the lane
        union(bar, tbox(x3 - wl / 2, P["lead_x_end"], yl - wl / 2, yl + wl / 2, zl - t, zl))       # axial run
        add(pl, bar, "Phase %s" % "ABC"[k], CU)
        add(pl, tcyl(x3, y3, -P["term_ac_h"] - 3.0, 4.0, P["scr_d"] + 1.0), "M5 screw AC %s" % "ABC"[k], GREY)

    # ---------------- cell aux / control board + FFC cables
    ax = new_comp(root, "Cell aux and control board")
    add(ax, tbox(P["aux_x0"], P["aux_x1"], P["aux_y0"], P["aux_y1"], 0, P["bt"]), "Aux PCB", GREEN)
    for i, (lab, dx, dy, w2, h2, hh) in enumerate((("75V-12V buck", 4, -18, 10, 8, 4), ("iso 6V HS A", 4, -6, 8, 6, 4),
                                                   ("iso 6V HS B", 4, 2, 8, 6, 4), ("iso 6V HS C", 4, 10, 8, 6, 4),
                                                   ("MCU", 15, -10, 6, 6, 1), ("fibre Rx/Tx", 15, 4, 8, 12, 9))):
        add(ax, tbox(P["aux_x0"] + dx, P["aux_x0"] + dx + w2, dy, dy + h2, P["bt"], P["bt"] + hh), lab, DARK)
    for k in range(n):
        x4 = xs[k] + J4[0]
        yf = P["ffc_lane_y"] + 0.0 * k
        f = tbox(x4 - 5.0, x4 + 5.0, J4[1] - 3.0, yf + 5.0, 4.6 + 0.35 * k, 4.9 + 0.35 * k)
        union(f, tbox(x4 - 5.0, P["aux_x0"] + 2.0, yf - 5.0, yf + 5.0, 4.6 + 0.35 * k, 4.9 + 0.35 * k))
        add(ax, f, "FFC %s" % "ABC"[k], INS)

    # ---------------- insulation sheet and motor housing segment
    hs = new_comp(root, "Motor housing segment")
    zb = min(P["lead_z"]) - P["lead_t"] - 0.5
    add(hs, tbox(P["plate_x0"] - 16, P["lead_x_end"], P["plate_y0"] - 4, P["plate_y1"] + 4, zb - P["ins_t"], zb),
        "Insulation sheet", INS, 0.6)
    add(hs, tbox(P["plate_x0"] - 16, P["lead_x_end"], P["plate_y0"] - 4, P["plate_y1"] + 4, P["housing_z1"] - P["housing_t"],
                 P["housing_z1"]), "Housing (stator jacket)", GREY, 0.35)


def run(context):
    try:
        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = adsk.fusion.Design.cast(app.activeProduct)
        design.designType = adsk.fusion.DesignTypes.DirectDesignType
        root = design.rootComponent
        root.name = "SPB cell (3 legs, 2x EPC2361 per switch)"
        build(root)
        app.activeViewport.fit()
        ui.messageBox("SPB cell assembly built.\nBoard STEP: %s" % STEP)
    except Exception:
        ui.messageBox("Failed:\n%s" % traceback.format_exc())
