"""Generates reports/report_values.tex (macros) and reports/table_tradeoff.tex (the
N-parallel trade-off table body) from the final design optimization, for \\input into
the paper-style LaTeX report. Run after scripts/run_epc2361_sweep_v2.py and
scripts/make_figures.py.
"""

import sys
from pathlib import Path

import yaml

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT / "src"))

from spb_bb.devices import load_device
from spb_bb.optimize import DesignSpec, design_sweep_over_n
from spb_bb.switching_loss import SwitchingLossModel
from spb_bb.ltspice.lookup import build_eon_interpolator, build_eoff_interpolator, load_sweep_csv

with open(PROJECT / "config" / "design_spec.yaml", "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f)

device = load_device(str(PROJECT / "data" / "devices" / "EPC2361.yaml"))

eon_rows = load_sweep_csv(str(PROJECT / "outputs" / "EPC2361_eon_sweep.csv"))
eoff_rows = load_sweep_csv(str(PROJECT / "outputs" / "EPC2361_eoff_sweep.csv"))
eon_fn = build_eon_interpolator(eon_rows)
eoff_fn = build_eoff_interpolator(eoff_rows)
sw_model = SwitchingLossModel(device, mode="lookup", eon_lookup_fn=eon_fn, eoff_lookup_fn=eoff_fn)

l_loop_nH_default = cfg["search"]["loop_inductance_sweep_nH"][1]

spec = DesignSpec(
    p_out_leg=cfg["power"]["p_out_leg_W"],
    v_dc=cfg["power"]["v_dc_V"],
    v_rms_fund=cfg["power"]["v_rms_fund_V"],
    power_factor=cfg["power"]["power_factor"],
    modulation_index=cfg["power"]["modulation_index"],
    efficiency_target=cfg["targets"]["efficiency_full_load"],
    t_dead=cfg["timing"]["dead_time_ns"] * 1e-9,
    t_ambient_c=cfg["thermal"]["t_ambient_C"],
    r_th_interface=cfg["thermal"]["r_th_interface_C_per_W"],
    r_th_sink_amb=cfg["thermal"]["r_th_sink_amb_C_per_W"],
    l_loop_nH=l_loop_nH_default,
    t_j_ceiling_c=cfg["targets"]["t_j_ceiling_C"],
    v_overshoot_max_frac=cfg["targets"]["v_overshoot_max_frac"],
    svm=(cfg["power"]["modulation_scheme"].upper() == "SVM"),
)

rg_on_bounds = (cfg["search"]["rg_on_min_ohm"], cfg["search"]["rg_on_max_ohm"])
rg_off_bounds = (cfg["search"]["rg_off_min_ohm"], cfg["search"]["rg_off_max_ohm"])
fsw_bounds = (cfg["search"]["fsw_min_Hz"], cfg["search"]["fsw_max_Hz"])
n_range = range(1, cfg["search"]["n_parallel_max"] + 1)

results = design_sweep_over_n(
    device, spec, sw_model, n_range=n_range, rg_on_bounds=rg_on_bounds,
    rg_off_bounds=rg_off_bounds, fsw_bounds=fsw_bounds, l_loop_nH=l_loop_nH_default,
)
feasible = [r for r in results if r.feasible]
best = max(feasible, key=lambda r: r.f_sw) if feasible else None

if best is None:
    raise SystemExit("No feasible design point -- cannot generate report values.")

macros = f"""% Auto-generated by scripts/make_report_values.py -- do not edit by hand.
\\newcommand{{\\NVAL}}{{{best.n_parallel}}}
\\newcommand{{\\RGONVAL}}{{{best.r_g_on:.1f}}}
\\newcommand{{\\RGOFFVAL}}{{{best.r_g_off:.1f}}}
\\newcommand{{\\FSWVAL}}{{{best.f_sw/1e3:.1f}}}
\\newcommand{{\\PTOTALVAL}}{{{best.p_total_leg:.2f}}}
\\newcommand{{\\PBUDGETVAL}}{{{best.p_budget_leg:.2f}}}
\\newcommand{{\\PCTVAL}}{{{100*best.p_total_leg/best.p_budget_leg:.0f}}}
\\newcommand{{\\TJVAL}}{{{best.t_junction_c:.1f}}}
\\newcommand{{\\MARGINVAL}}{{{best.margin_c:.1f}}}
\\newcommand{{\\OVSVAL}}{{{best.v_ds_overshoot:.1f}}}
"""
(PROJECT / "reports" / "report_values.tex").write_text(macros, encoding="utf-8")
print("Wrote reports/report_values.tex")
print(macros)

table_lines = [
    "\\begin{table}[t]",
    "\\centering\\footnotesize",
    f"\\caption{{$f_{{sw}}$ vs.\\ parallel-device-count trade-off at $L_{{loop}}$={l_loop_nH_default:g}\\,nH (feasible points only).}}",
    "\\label{tab:tradeoff}",
    "\\begin{tabular}{@{}rrrrrrrr@{}}",
    "\\toprule",
    "$N$ & $R_{g,on}$ & $R_{g,off}$ & $f_{sw}$ & $P_{total}$ & $T_J$ & Margin & Ovs. \\\\",
    " & (\\ohm) & (\\ohm) & (kHz) & (W) & (\\degC) & (\\degC) & (V) \\\\",
    "\\midrule",
]
for r in results:
    row = (
        f"{r.n_parallel} & {r.r_g_on:.1f} & {r.r_g_off:.1f} & {r.f_sw/1e3:.1f} & "
        f"{r.p_total_leg:.2f} & {r.t_junction_c:.1f} & {r.margin_c:.1f} & "
        f"{r.v_ds_overshoot:.1f} \\\\"
    )
    if r is best:
        row = "\\textbf{" + row.replace(" & ", "} & \\textbf{").replace(" \\\\", "} \\\\")
    table_lines.append(row)
table_lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
(PROJECT / "reports" / "table_tradeoff.tex").write_text("\n".join(table_lines), encoding="utf-8")
print("Wrote reports/table_tradeoff.tex")

skipped = [n for n in n_range if n not in [r.n_parallel for r in results]]
if skipped:
    print(f"N skipped as infeasible: {skipped}")
