%% ========================================================================
% SPECIFIC ON-RESISTANCE VERSUS BREAKDOWN VOLTAGE
%
% Curves:
%   1. Si theoretical limit
%   2. 4H-SiC theoretical limit
%   3. GaN theoretical limit
%
% Axes:
%   Breakdown voltage [V]
%   Specific on-resistance [mOhm cm^2]
%
% ========================================================================

clear;
clc;
close all;

%% ========================================================================
% BREAKDOWN-VOLTAGE RANGE
% ========================================================================

Vbr = logspace(1,3,500);   % 10 V to 1000 V

%% ========================================================================
% THEORETICAL / APPROXIMATE LIMIT CURVES
%
% Units:
%   Vbr   -> V
%   Ronsp -> mOhm cm^2
%
% ========================================================================

%% Silicon limit

RonSi = 4.75e-6 .* Vbr.^2.52;

%% 4H-SiC limit

RonSiC = 2.0e-7 .* Vbr.^2;

%% GaN limit

RonGaN = 5.0e-8 .* Vbr.^2;

%% ========================================================================
% CREATE FIGURE
% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 23 17]);

ax = axes(fig);

hold(ax,'on');
box(ax,'on');

%% ========================================================================
% COLORS
% ========================================================================

cSi  = [0.00 0.00 1.00];
cSiC = [0.00 0.45 0.75];
cGaN = [1.00 0.00 0.00];

lineWidth = 4;

%% ========================================================================
% PLOT CURVES
% ========================================================================

hSi = loglog( ...
    Vbr, ...
    RonSi, ...
    'Color',cSi, ...
    'LineWidth',lineWidth);

hSiC = loglog( ...
    Vbr, ...
    RonSiC, ...
    'Color',cSiC, ...
    'LineWidth',lineWidth);

hGaN = loglog( ...
    Vbr, ...
    RonGaN, ...
    'Color',cGaN, ...
    'LineWidth',lineWidth);

%% ========================================================================
% AXIS LIMITS
% ========================================================================

xlim(ax,[10 1000]);
ylim(ax,[1e-4 1e4]);

%% ========================================================================
% AXIS FORMATTING
% ========================================================================

ax.XScale = 'log';
ax.YScale = 'log';

ax.FontName = 'Times New Roman';
ax.FontSize = 20;

ax.LineWidth = 1.3;

ax.TickDir = 'in';
ax.TickLength = [0.012 0.012];

%% Grid

grid(ax,'on');

ax.XMinorGrid = 'on';
ax.YMinorGrid = 'on';

ax.GridLineStyle = ':';
ax.MinorGridLineStyle = ':';

ax.GridAlpha = 0.55;
ax.MinorGridAlpha = 0.35;

ax.GridColor = [0 0 0];
ax.MinorGridColor = [0 0 0];

%% ========================================================================
% AXIS LABELS
% ========================================================================

xlabel( ...
    ax, ...
    'Breakdown voltage [V]', ...
    'FontName','Times New Roman', ...
    'FontSize',20);

ylabel( ...
    ax, ...
    'Specific on-resistance [m\Omega cm^2]', ...
    'FontName','Times New Roman', ...
    'FontSize',20);

% title( ...
%     ax, ...
%     'Specific on-resistance versus breakdown voltage', ...
%     'FontName','Times New Roman', ...
%     'FontSize',20, ...
%     'FontWeight','bold');

%% ========================================================================
% LEGEND
% ========================================================================

lgd = legend( ...
    [hSi hSiC hGaN], ...
    { ...
    'Si limit', ...
    '4H-SiC limit', ...
    'GaN limit' ...
    }, ...
    'Location','northwest');

lgd.FontName = 'Times New Roman';
lgd.FontSize = 18;
lgd.FontWeight = 'bold';

lgd.Box = 'on';

%% ========================================================================
% REFERENCE VOLTAGE LINES
% ========================================================================

% Vref1 = 200;
% Vref2 = 600;
% 
% xline( ...
%     ax, ...
%     Vref1, ...
%     '--k', ...
%     'LineWidth',2.2, ...
%     'HandleVisibility','off');
% 
% xline( ...
%     ax, ...
%     Vref2, ...
%     '--k', ...
%     'LineWidth',2.2, ...
%     'HandleVisibility','off');

%% ========================================================================
% REFERENCE VOLTAGE LABELS
% ========================================================================

% text( ...
%     ax, ...
%     175, ...
%     1.7e-4, ...
%     '200 V', ...
%     'FontName','Times New Roman', ...
%     'FontSize',13, ...
%     'FontWeight','bold', ...
%     'HorizontalAlignment','center');
% 
% text( ...
%     ax, ...
%     520, ...
%     1.7e-4, ...
%     '600 V', ...
%     'FontName','Times New Roman', ...
%     'FontSize',13, ...
%     'FontWeight','bold', ...
%     'HorizontalAlignment','center');

%% ========================================================================
% CURVE LABELS
% ========================================================================

% text( ...
%     ax, ...
%     500, ...
%     1.2e3, ...
%     'Si limit', ...
%     'FontName','Times New Roman', ...
%     'FontSize',16, ...
%     'FontWeight','bold');
% 
% text( ...
%     ax, ...
%     50, ...
%     3e-2, ...
%     '4H-SiC limit', ...
%     'FontName','Times New Roman', ...
%     'FontSize',16, ...
%     'FontWeight','bold');
% 
% text( ...
%     ax, ...
%     480, ...
%     1.1e-3, ...
%     'GaN limit', ...
%     'FontName','Times New Roman', ...
%     'FontSize',16, ...
%     'FontWeight','bold');

%% ========================================================================
% OPTIONAL ARROWS
%
% These arrows are only graphical annotations.
% You can move or delete them manually.
% ========================================================================

%% Silicon arrow

% annotation( ...
%     fig, ...
%     'textarrow', ...
%     [0.84 0.82], ...
%     [0.78 0.68], ...
%     'String','', ...
%     'LineWidth',3, ...
%     'HeadLength',10, ...
%     'HeadWidth',10);

%% SiC arrow

% annotation( ...
%     fig, ...
%     'textarrow', ...
%     [0.49 0.49], ...
%     [0.42 0.32], ...
%     'String','', ...
%     'LineWidth',3, ...
%     'HeadLength',10, ...
%     'HeadWidth',10);

%% GaN arrow

    % fig, ...
    % 'textarrow', ...
    % [0.81 0.81], ...
    % [0.25 0.34], ...
    % 'String','', ...
    % 'LineWidth',3, ...
    % 'HeadLength',10, ...
    % 'HeadWidth',10);annotation( ...


%% ========================================================================
% ENABLE MANUAL EDITING
% ========================================================================

plotedit(fig,'on');

%% ========================================================================
% EXPORT COMMANDS
%
% Run these manually after arranging labels/arrows if needed.
% ========================================================================

% Save editable figure:
%
% savefig(gcf,'Ronsp_vs_BreakdownVoltage.fig');

% Export vector PDF:
%
% exportgraphics( ...
%     gcf, ...
%     'Ronsp_vs_BreakdownVoltage.pdf', ...
%     'ContentType','vector', ...
%     'BackgroundColor','white');

% Export PNG:
%
% exportgraphics( ...
%     gcf, ...
%     'Ronsp_vs_BreakdownVoltage.png', ...
%     'Resolution',600, ...
%     'BackgroundColor','white');