M48
; DRILL file {KiCad 7.0.10} date Tue Sep 22 21:52:45 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-22T21:52:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X40.0Y-8.0
X40.0Y-53.0
X74.0Y-8.0
X74.0Y-53.0
T2
X75.0Y-27.0
X75.0Y-43.0
M30
