"""Reproduce the 300-kW repeated-block estimate; no four-parallel FEM run is implied.
Run from any directory: python case_300kw.py
Inputs: archived v4 two-parallel model coefficients and M=1.15 network losses.
Outputs: case_results.json, case_numbers.tex, loss_rows.tex.
"""
from pathlib import Path
import json, math
HERE=Path(__file__).resolve().parent
d=json.loads((HERE/'case_inputs.json').read_text())
P,V,N,M,f=300000.,1200.,16,1.15,50000.
I=2*math.sqrt(2)*P/(3*M*V)
Ib=I/2; scale=Ib/100.; spec=d['spec']; q=d['network_at_M115']
# Exact sine-period average of a quadratic energy fit a*i^2+b*|i|+c.
def avg_energy(c):return c[0]*Ib**2+c[1]*2*math.sqrt(2)*Ib/math.pi+c[2]
parts={
 'Conduction':2*Ib**2*spec['Rds_25_typ']*spec['Rds_factor_100C']/2,
 'Switching':2*f*(avg_energy(d['energy_fit_on'])+avg_energy(d['energy_fit_off'])),
 'PCB copper (load)':2*q['cu_lf']*scale**2,
 'PCB copper (harmonics)':2*q['cu_hf']*scale**2,
 'Capacitor ESR':2*q['caps']*scale**2,
 'Dead time':2*f*2*spec['t_dead']*(spec['Vsd0']*Ib*math.sqrt(2)*2/math.pi+spec['Rsd']/2*Ib**2),
 'Gate drive and LDO':2*d['gate_ldo_W']}
loss=sum(parts.values()); total=3*N*loss; eta=100*P/(P+total)
area=2*30*28.2/100 # sum of two board footprints, cm2; not enclosure volume
worst=d['bank']['dVpp_shared_3ph']*scale/75*100
res=dict(P_output_W=P,V_bus_V=V,N=N,n_parallel=4,drivers_per_leg=2,
 phase_current_Arms=I,device_count=6*N*4,driver_count=3*N*2,
 losses_per_leg_W=parts,loss_per_leg_W=loss,loss_stack_W=total,
 efficiency_percent=eta,PCB_area_per_leg_cm2=area,
 PCB_area_density_kW_cm2=(P/(3*N)/1000)/area,
 C_nominal_per_leg_uF=504,C_effective_per_leg_uF=154.8,
 C_nominal_per_cell_uF=1512,C_effective_per_cell_uF=464.4,
 worst_grid_ripple_percent=worst,
 boundary='Repeated independent blocks, equal sharing, 75 V, M=1.15, unity PF, 50 kHz, Rds at 100 C; excludes external auxiliaries, inter-block busbars, cooling and machine losses. Switching uses v4 terminal-energy fits pending dissipative-energy reconciliation.')
(HERE/'case_results.json').write_text(json.dumps(res,indent=2)+'\n')
mac={'CaseCurrent':f'{I:.1f}','CaseLegLoss':f'{loss:.2f}','CaseTotalLoss':f'{total/1000:.2f}',
 'CaseEfficiency':f'{eta:.2f}','CaseAreaDensity':f'{res["PCB_area_density_kW_cm2"]:.2f}',
 'CaseRippleWorst':f'{worst:.2f}'}
(HERE/'case_numbers.tex').write_text('% Generated by case_300kw.py\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in mac.items()))
(HERE/'loss_rows.tex').write_text('% Generated by case_300kw.py\n'+r'\newcommand{\CaseLossRows}{%'+'\n'+''.join(f'{k} & {v:.2f} & {3*N*v:.1f} '+r'\\'+'\n' for k,v in parts.items())+'}\n')
assert abs(sum(parts.values())-loss)<1e-10
assert 6*N*4==384 and 3*N*2==96
print(json.dumps(res,indent=2))
