%% ========================================================================
% SPB CELL-COUNT SCALING FOR A 1200-V DC LINK
%
% Aligned with the updated manuscript table:
%
% N = 1   -> 1200 V/cell -> 1700-2000-V SiC
% N = 2   ->  600 V/cell -> 900-1200-V class
% N = 3   ->  400 V/cell -> 650-V GaN / SiC
% N = 4   ->  300 V/cell -> 650-V or lower-voltage class
% N = 5   ->  240 V/cell -> 350-V class
% N = 8   ->  150 V/cell -> 200-V class
% N = 10  ->  120 V/cell -> 150-V class
% N = 15  ->   80 V/cell -> 100-V GaN / MOSFET class
%
% Nominal cell voltage:
%       Vcell = Vdc/N
%
% Active switches:
%       Nsw = 6N
%
% ========================================================================

clear;
clc;
close all;

%% ========================================================================
% SYSTEM PARAMETERS
% ========================================================================

Vdc = 1200;                    % Total dc-link voltage [V]

% Full sweep
N = 1:15;

% Cell voltage
Vcell = Vdc ./ N;

% Total active switches
Nswitch = 6 .* N;

%% ========================================================================
% TABLE CELL COUNTS
% ========================================================================

N_table = [ ...
    1, ...
    2, ...
    3, ...
    4, ...
    5, ...
    8, ...
    10, ...
    15 ...
    ];

Vcell_table = Vdc ./ N_table;

Nswitch_table = 6 .* N_table;

%% ========================================================================
% MAIN DEVICE-CLASS TRANSITION POINTS
%
% These are the lower-voltage classes emphasized in the table.
% ========================================================================

N_selected = [ ...
     3, ...     % 650-V class
     5, ...     % 350-V class
     8, ...     % 200-V class
    10, ...     % 150-V class
    15  ...     % 100-V class
    ];

V_selected = Vdc ./ N_selected;

deviceClass = [ ...
    650, ...
    350, ...
    200, ...
    150, ...
    100 ...
    ];

deviceLabels = { ...
    '650-V class', ...
    '350-V class', ...
    '200-V class', ...
    '150-V class', ...
    '100-V class' ...
    };

%% ========================================================================
% FIGURE SETTINGS
% ========================================================================

figureWidth  = 20;      % cm
figureHeight = 11;      % cm

fontName = 'Times New Roman';

axisFontSize   = 11;
labelFontSize  = 12;
legendFontSize = 10;

cellLineWidth   = 2.2;
switchLineWidth = 2.0;

markerSize = 6.5;

%% ========================================================================
% COLORS
% ========================================================================

% Cell-voltage curve
cCell = [0.08 0.35 0.72];

% Switch-count curve
cSwitch = [0.62 0.24 0.46];

% Device-class colors
c650 = [0.82 0.20 0.16];
c350 = [0.90 0.52 0.10];
c200 = [0.18 0.58 0.32];
c150 = [0.10 0.55 0.68];
c100 = [0.35 0.35 0.35];

deviceColors = [ ...
    c650; ...
    c350; ...
    c200; ...
    c150; ...
    c100 ...
    ];

gridColor = [0.86 0.86 0.86];

%% ========================================================================
% CREATE FIGURE
% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 figureWidth figureHeight]);

ax = axes(fig);

hold(ax,'on');

%% ========================================================================
% LEFT Y-AXIS: NOMINAL CELL VOLTAGE
% ========================================================================

yyaxis left

hCell = plot( ...
    N, ...
    Vcell, ...
    '-o', ...
    'Color',cCell, ...
    'LineWidth',cellLineWidth, ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',cCell);

ylabel( ...
    'Nominal cell voltage, V_{dc}/N (V)', ...
    'FontName',fontName, ...
    'FontSize',labelFontSize, ...
    'Interpreter','tex');

ylim([0 1250]);

yticks(0:200:1200);

ax.YColor = [0.15 0.15 0.15];

%% ========================================================================
% DEVICE-CLASS HORIZONTAL LINES
% ========================================================================

for k = 1:length(deviceClass)

    yline( ...
        deviceClass(k), ...
        '--', ...
        'Color',deviceColors(k,:), ...
        'LineWidth',1.25, ...
        'HandleVisibility','off');

end

%% ========================================================================
% DEVICE-CLASS LABELS
%
% Put labels near the right-hand side.
% ========================================================================

deviceLabelX = [ ...
    11.3, ...
    11.3, ...
    11.3, ...
    11.3, ...
    11.3 ...
    ];

deviceLabelYOffset = [ ...
    18, ...
    18, ...
    18, ...
    18, ...
    18 ...
    ];

for k = 1:length(deviceClass)

    text( ...
        deviceLabelX(k), ...
        deviceClass(k) + deviceLabelYOffset(k), ...
        deviceLabels{k}, ...
        'FontName',fontName, ...
        'FontSize',9.5, ...
        'FontWeight','bold', ...
        'Color',deviceColors(k,:), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','bottom');

end

%% ========================================================================
% SHOW ALL CELL COUNTS INCLUDED IN THE TABLE
%
% These are black-edged markers so that the figure matches Table I.
% ========================================================================

plot( ...
    N_table, ...
    Vcell_table, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',7.5, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',[0.20 0.20 0.20], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

%% ========================================================================
% HIGHLIGHT SELECTED DEVICE-CLASS TRANSITIONS
% ========================================================================

for k = 1:length(N_selected)

    plot( ...
        N_selected(k), ...
        V_selected(k), ...
        'o', ...
        'LineStyle','none', ...
        'MarkerSize',10, ...
        'MarkerFaceColor',deviceColors(k,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',1.2, ...
        'HandleVisibility','off');

end

%% ========================================================================
% RECTANGULAR DESIGN INDICATORS
%
% Each rectangle connects:
%       selected N
%       device-voltage class
%
% The top of the rectangle represents the device-class rating.
% The marker inside it represents the actual nominal cell voltage.
% ========================================================================

rectangleWidth = 0.34;

for k = 1:length(N_selected)

    rectangle( ...
        'Position',[ ...
            N_selected(k) - rectangleWidth/2, ...
            0, ...
            rectangleWidth, ...
            deviceClass(k)], ...
        'EdgeColor',deviceColors(k,:), ...
        'LineStyle',':', ...
        'LineWidth',1.4);

end

%% ========================================================================
% SELECTED N LABELS
% ========================================================================

NlabelY = [ ...
    445, ...    % N=3
    285, ...    % N=5
    180, ...    % N=8
    128, ...    % N=10
     55  ...    % N=15
    ];

NlabelXoffset = [ ...
    0.20, ...
    0.20, ...
    0.20, ...
    0.20, ...
   -0.20 ...
    ];

for k = 1:length(N_selected)

    text( ...
        N_selected(k) + NlabelXoffset(k), ...
        NlabelY(k), ...
        sprintf('N = %d',N_selected(k)), ...
        'FontName',fontName, ...
        'FontSize',9.5, ...
        'FontWeight','bold', ...
        'Color',deviceColors(k,:), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle');

end

%% ========================================================================
% N = 1 HIGH-VOLTAGE SIC LABEL
% ========================================================================

text( ...
    1.20, ...
    1150, ...
    '1700--2000-V SiC', ...
    'FontName',fontName, ...
    'FontSize',9.5, ...
    'Color',[0.20 0.20 0.20], ...
    'HorizontalAlignment','left');

%% ========================================================================
% N = 2 HIGHER-VOLTAGE DEVICE CLASS
% ========================================================================

text( ...
    2.18, ...
    635, ...
    '900--1200-V class', ...
    'FontName',fontName, ...
    'FontSize',9.5, ...
    'Color',[0.20 0.20 0.20], ...
    'HorizontalAlignment','left');

%% ========================================================================
% N = 4 LABEL
% ========================================================================

text( ...
    4.15, ...
    325, ...
    '650-V or lower', ...
    'FontName',fontName, ...
    'FontSize',9.0, ...
    'Color',[0.30 0.30 0.30], ...
    'HorizontalAlignment','left');

%% ========================================================================
% RIGHT Y-AXIS: ACTIVE SWITCH COUNT
% ========================================================================

yyaxis right

hSwitch = plot( ...
    N, ...
    Nswitch, ...
    '-s', ...
    'Color',cSwitch, ...
    'LineWidth',switchLineWidth, ...
    'MarkerSize',markerSize, ...
    'MarkerFaceColor',cSwitch, ...
    'MarkerEdgeColor',cSwitch);

ylabel( ...
    'Total active switches, 6N', ...
    'FontName',fontName, ...
    'FontSize',labelFontSize, ...
    'Interpreter','tex');

ylim([0 100]);

yticks(0:20:100);

ax.YColor = cSwitch;

%% ========================================================================
% X AXIS
% ========================================================================

xlabel( ...
    'SPB cell count, N', ...
    'FontName',fontName, ...
    'FontSize',labelFontSize, ...
    'Interpreter','tex');

xlim([1 15.5]);

xticks([ ...
    1 2 3 4 5 6 8 10 12 15 ...
    ]);

%% ========================================================================
% AXIS FORMATTING
% ========================================================================

ax.FontName = fontName;
ax.FontSize = axisFontSize;

ax.LineWidth = 1.0;

ax.TickDir = 'out';
ax.TickLength = [0.012 0.012];

ax.Box = 'on';

ax.XGrid = 'on';
ax.YGrid = 'on';

ax.GridColor = gridColor;
ax.GridAlpha = 0.50;

ax.Layer = 'top';

%% ========================================================================
% LEGEND
% ========================================================================

lgd = legend( ...
    [hCell hSwitch], ...
    { ...
    'Nominal cell voltage, V_{dc}/N', ...
    'Total active switches, 6N' ...
    }, ...
    'Location','northwest');

lgd.FontName = fontName;
lgd.FontSize = legendFontSize;
lgd.Interpreter = 'tex';
lgd.Box = 'off';

%% ========================================================================
% MANUAL EDITING
% ========================================================================

plotedit(fig,'on');

%% ========================================================================
% EXPORT
% ========================================================================

% Save editable MATLAB figure:
%
% savefig(fig,'SPB_CellCount_1200V_TableAligned.fig');

% Export vector PDF:
%
% exportgraphics( ...
%     fig, ...
%     'SPB_CellCount_1200V_TableAligned.pdf', ...
%     'ContentType','vector', ...
%     'BackgroundColor','white');

% Export high-resolution PNG:
%
% exportgraphics( ...
%     fig, ...
%     'SPB_CellCount_1200V_TableAligned.png', ...
%     'Resolution',600, ...
%     'BackgroundColor','white');