%% Plot off-the-shelf GaN devices:
% 1) Coss vs. RDS(on)
% 2) D-FOM vs. voltage class
%
% Color  = vendor / brand
% Marker = voltage class

clear; clc; close all;

%% User settings
excelFile = "GaN_device_database.xlsx";
sheetName = "GaN_Device_Table";

capVar = "Coss_pF";
rdsVar = "RDSon_max_mOhm";

% Optional:
% If you have Qoss in the database, set this to true
useQoss = false;
qossVar = "Qoss_nC";

%% Read Excel table
T = readtable(excelFile, ...
    "Sheet", sheetName, ...
    "VariableNamingRule", "preserve");

T.Properties.VariableNames = matlab.lang.makeValidName( ...
    T.Properties.VariableNames);

capVar  = matlab.lang.makeValidName(capVar);
rdsVar  = matlab.lang.makeValidName(rdsVar);
qossVar = matlab.lang.makeValidName(qossVar);

%% Remove rows with missing basic data
validRows = ...
    ~isnan(T.(capVar)) & ...
    ~isnan(T.(rdsVar)) & ...
    ~isnan(T.Voltage_V);

T = T(validRows,:);

%% Sort table by voltage and then RDS(on)
T = sortrows(T, ...
    {'Voltage_V', char(rdsVar)}, ...
    {'ascend','ascend'});

%% Extract vendors and voltage classes
vendors = unique(string(T.Vendor), "stable");
voltageLevels = unique(T.Voltage_V, "stable");

%% Plot settings
markerList = {'o','s','^','d','v','>','<','p','h','x','+'};

if numel(voltageLevels) > numel(markerList)
    error("Not enough marker types for all voltage levels.");
end

colors = lines(numel(vendors));

%% =========================================================
%  D-FOM CALCULATION
% ==========================================================

% Convert RDS(on) from mOhm to Ohm
Rds_Ohm = T.(rdsVar) * 1e-3;

if useQoss && ismember(qossVar,T.Properties.VariableNames)

    % -------------------------------------------------------
    % Preferred method:
    %
    % Coss,Q = Qoss / V
    %
    % Qoss in Coulomb
    % V in Volt
    % -------------------------------------------------------

    Qoss_C = T.(qossVar) * 1e-9;

    CossQ_F = Qoss_C ./ T.Voltage_V;

    T.DFOM = 1 ./ sqrt(Rds_Ohm .* CossQ_F);

    dFOMlabel = ...
        'D-FOM = 1/\surd(R_{DS(on)} C_{oss,Q})';

else

    % -------------------------------------------------------
    % Approximation using datasheet Coss
    %
    % Coss in pF --> F
    % -------------------------------------------------------

    Coss_F = T.(capVar) * 1e-12;

    T.DFOM = 1 ./ sqrt(Rds_Ohm .* Coss_F);

    dFOMlabel = ...
        'Approx. D-FOM = 1/\surd(R_{DS(on)} C_{oss})';
end


%% =========================================================
%  FIGURE 1: Coss vs RDS(on)
% ==========================================================

fig1 = figure( ...
    'Color','w', ...
    'Position',[100 100 1400 850]);

ax = axes(fig1, ...
    'Position',[0.08 0.13 0.60 0.78]);

hold(ax,'on');
grid(ax,'on');
box(ax,'on');

%% Plot each device
for i = 1:height(T)

    vendorIdx = find( ...
        vendors == string(T.Vendor(i)),1);

    voltageIdx = find( ...
        voltageLevels == T.Voltage_V(i),1);

    scatter(ax, ...
        T.(capVar)(i), ...
        T.(rdsVar)(i), ...
        120, ...
        'Marker',markerList{voltageIdx}, ...
        'MarkerEdgeColor',colors(vendorIdx,:), ...
        'MarkerFaceColor',colors(vendorIdx,:), ...
        'LineWidth',1.3);

    text(ax, ...
        T.(capVar)(i)*1.06, ...
        T.(rdsVar)(i)*1.06, ...
        string(T.Device(i)), ...
        'FontSize',8, ...
        'Interpreter','none');
end

%% Axis settings
set(ax, ...
    'XScale','log', ...
    'YScale','log');

set(ax, ...
    'FontSize',12, ...
    'LineWidth',1.1);

xlabel(ax, ...
    'Output capacitance, C_{oss} (pF)', ...
    'Interpreter','tex', ...
    'FontSize',13);

ylabel(ax, ...
    'On-state resistance, R_{DS(on),max} (m\Omega)', ...
    'Interpreter','tex', ...
    'FontSize',13);

title(ax, ...
    'Off-the-shelf GaN devices: C_{oss} vs. R_{DS(on)}', ...
    'Interpreter','tex', ...
    'FontSize',14);

xlim(ax,[8 3000]);
ylim(ax,[0.5 600]);

%% Vendor legend
vendorHandles = gobjects(numel(vendors),1);

for k = 1:numel(vendors)

    vendorHandles(k) = scatter(ax, ...
        nan,nan,120,'o', ...
        'MarkerEdgeColor',colors(k,:), ...
        'MarkerFaceColor',colors(k,:), ...
        'LineWidth',1.3);

end

lgdVendor = legend(ax, ...
    vendorHandles, ...
    vendors, ...
    'Location','northeastoutside', ...
    'Interpreter','none');

title(lgdVendor,'Vendor');

%% Manual voltage-class legend
axV = axes(fig1, ...
    'Position',[0.72 0.18 0.23 0.35]);

hold(axV,'on');
axis(axV,'off');

text(axV, ...
    0.00,1.05, ...
    'Voltage class', ...
    'FontWeight','bold', ...
    'FontSize',11, ...
    'Units','normalized');

for k = 1:numel(voltageLevels)

    y = 1.0 - 0.10*k;

    scatter(axV, ...
        0.12,y,120, ...
        'Marker',markerList{k}, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','k', ...
        'LineWidth',1.3);

    text(axV, ...
        0.25,y, ...
        string(voltageLevels(k)) + " V", ...
        'FontSize',10, ...
        'VerticalAlignment','middle');

end

xlim(axV,[0 1]);
ylim(axV,[0 1]);

exportgraphics( ...
    fig1, ...
    'GaN_Coss_vs_RDSon_expanded.png', ...
    'Resolution',300);


%% =========================================================
%  FIGURE 2: D-FOM vs Voltage Rating
% ==========================================================

fig2 = figure( ...
    'Color','w', ...
    'Position',[150 120 1300 750]);

ax2 = axes(fig2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

for i = 1:height(T)

    vendorIdx = find( ...
        vendors == string(T.Vendor(i)),1);

    voltageIdx = find( ...
        voltageLevels == T.Voltage_V(i),1);

    scatter(ax2, ...
        T.Voltage_V(i), ...
        T.DFOM(i), ...
        120, ...
        'Marker',markerList{voltageIdx}, ...
        'MarkerEdgeColor',colors(vendorIdx,:), ...
        'MarkerFaceColor',colors(vendorIdx,:), ...
        'LineWidth',1.3);

    text(ax2, ...
        T.Voltage_V(i)*1.02, ...
        T.DFOM(i)*1.02, ...
        string(T.Device(i)), ...
        'FontSize',8, ...
        'Interpreter','none');

end

set(ax2, ...
    'XScale','log', ...
    'YScale','log');

set(ax2, ...
    'FontSize',12, ...
    'LineWidth',1.1);

xlabel(ax2, ...
    'Rated blocking voltage, V_{DS} (V)', ...
    'FontSize',13);

ylabel(ax2, ...
    dFOMlabel, ...
    'Interpreter','tex', ...
    'FontSize',13);

title(ax2, ...
    'GaN Device Figure-of-Merit versus Blocking Voltage', ...
    'FontSize',14);

%% Vendor legend
vendorHandles2 = gobjects(numel(vendors),1);

for k = 1:numel(vendors)

    vendorHandles2(k) = scatter(ax2, ...
        nan,nan,120,'o', ...
        'MarkerEdgeColor',colors(k,:), ...
        'MarkerFaceColor',colors(k,:), ...
        'LineWidth',1.3);

end

legend(ax2, ...
    vendorHandles2, ...
    vendors, ...
    'Location','best', ...
    'Interpreter','none');

exportgraphics( ...
    fig2, ...
    'GaN_DFOM_vs_Voltage.png', ...
    'Resolution',300);


%% =========================================================
%  PRINT BEST D-FOM DEVICE FOR EACH VOLTAGE CLASS
% ==========================================================

fprintf('\n');
fprintf('Best D-FOM device for each voltage class:\n');
fprintf('-------------------------------------------------------------\n');

for k = 1:numel(voltageLevels)

    V = voltageLevels(k);

    idx = T.Voltage_V == V;

    Ttemp = T(idx,:);

    [bestDFOM,bestIdx] = max(Ttemp.DFOM);

    fprintf( ...
        '%4g V : %-25s  D-FOM = %.4g\n', ...
        V, ...
        string(Ttemp.Device(bestIdx)), ...
        bestDFOM);

end

fprintf('-------------------------------------------------------------\n');

disp("Plots saved as:");
disp("  GaN_Coss_vs_RDSon_expanded.png");
disp("  GaN_DFOM_vs_Voltage.png");