from pathlib import Path
import numpy as np
p=Path(__file__).resolve().parents[2];d=p/'Figures/Section-CommonMode'
# Finite raised-cosine transitions prevent unphysical impulses.
t=np.linspace(0,2,40001);tr=.004;td=.003
edges=np.array([.12,.27,.45,.55,.73,.88]);steps=np.array([1,1,1,-1,-1,-1])/3
edges=np.concatenate([edges,edges+1]);steps=np.tile(steps,2)

def waveform(delay):
 v=np.zeros_like(t);dv=np.zeros_like(t)
 for edge,step in zip(edges,steps):
  x=(t-edge-delay)/tr
  v+=step*np.where(x<=0,0,np.where(x>=1,1,(1-np.cos(np.pi*np.clip(x,0,1)))/2))
  dv+=step*np.where((x>0)&(x<1),np.pi/(2*tr)*np.sin(np.pi*np.clip(x,0,1)),0)
 return v,dv
v1,dv1=waveform(0);q2,dq2=waveform(td);v2=2-q2;vs=v1+v2;i=tr*(dv1-dq2)
# Two equal winding-to-frame capacitances Cg; common frame-to-ground
# return impedance Rg+s*Lg. KCL gives I/Vsum=s*Cg/(1+2*Rg*Cg*s+2*Lg*Cg*s^2).
# Illustrative underdamped response: omega0=1/sqrt(2*Lg*Cg),
# zeta=Rg*Cg*omega0. Compute periodic response analytically in frequency domain.
zeta=.22; f0_over_fsw=65.;omega0=2*np.pi*f0_over_fsw
u=vs[:-1]-2;dt=t[1]-t[0]
w=2*np.pi*np.fft.rfftfreq(len(u),dt);r=w/omega0
transfer=1j*r/(1-r*r+2j*zeta*r)
# Raw current normalized by Cg*Vc*omega0.
iraw=np.fft.irfft(np.fft.rfft(u)*transfer,n=len(u))
Ipk=np.max(np.abs(iraw));i=np.r_[iraw,iraw[0]]/Ipk
assert abs(np.mean(iraw))<1e-12
assert np.mean(u*iraw)>0 # Positive dissipation for the passive return network.
assert np.max(np.abs(vs-2))<=1/3+1e-12
# Save a regenerable generator, not just hand-drawn spikes.
head=r'''% Finite-rise complementary switching with td/Tsw=.003, tr/Tsw=.004.
% Generated by generate_cm_nonideal.py; current includes a passive RLC return path.
\begin{tikzpicture}[font=\footnotesize,>=latex,
 box/.style={draw=black!65,align=center,text width=2.6cm,minimum height=.9cm,inner sep=3pt}]
\node[box,fill=pesred!6] (b) at (1.2,3.6)
 {Cell 2\\[2pt]$3V_c/2-u(t)+\Delta v(t)$};
\node[box,fill=pesblue!6] (a) at (1.2,1.8)
 {Cell 1\\[2pt]$V_c/2+u(t)$};
\node[box,fill=pesgreen!6] (c) at (1.2,0)
 {\textcolor{pesgreen}{$v_{\Sigma}=2V_c+\Delta v(t)$}\\[2pt]
 \textcolor{pespurple}{CM return path: $R_g,L_g$}};
\draw[->] (a.south)--(c.north);
\draw[->] (b.west)--++(-.17,0)|-(c.west);
\foreach \y/\lo/\mid/\hi/\k in {3.6/1/1.5/2/2,1.8/0/0.5/1/1}{
 \draw[->,black!65] (4,\y-.58)--(7.4,\y-.58);
 \draw[->,black!65] (4,\y-.58)--(4,\y+.65);
 \foreach \dy/\lab in {-.45/\lo,0/\mid,.45/\hi}{
  \draw (4,\y+\dy)--(4.06,\y+\dy);
  \node[anchor=east] at (3.94,\y+\dy) {$\lab$};
 }
 \node[rotate=90] at (2.98,\y) {$v_{\mathrm{cm},\k}^{\mathrm{abs}}/V_c$};
 \draw[densely dotted,black!25] (4.08,\y)--(7.2,\y);
}
\draw[->,black!65] (4,-.65)--(7.4,-.65);
\draw[->,pesgreen] (4,-.65)--(4,.66);

\node[rotate=90,pesgreen] at (2.98,0) {$v_{\Sigma}/V_c$};

\foreach \dy/\v/\i in {-.45/1.5/-0.5,0/2/0,.45/2.5/0.5}{
 \draw[pesgreen] (4,\dy)--(4.06,\dy);
 \node[anchor=east,pesgreen] at (3.94,\dy) {$\v$};


}
\draw[densely dotted,black!25] (4.08,0)--(7.2,0);
'''
def compact_points(values):
 # Remove only collinear points (flat segments); retain resolved pulse edges.
 keep=np.r_[True,np.abs(np.diff(values,2))>1e-12,True]
 return t[keep],values[keep]
parts=[head]
for values,mid,row,col,style in [(v2,1.5,3.6,'pesred',''),(v1,.5,1.8,'pesblue',''),(vs,2,0,'pesgreen','')]:
 pts=[(4.08+1.56*x,row+.9*(v-mid)) for x,v in zip(*compact_points(values))]
 parts.append('\\draw['+col+',line width=.75pt'+style+'] '+'--'.join(f'({x:.4f},{y:.4f})' for x,y in pts)+';\n')
parts.append(r'''\foreach \x/\lab in {4.08/0,5.64/1,7.2/2}{
 \draw (\x,-.65)--(\x,-.58);
 \node[anchor=north] at (\x,-.67) {$\lab$};
}
\node[anchor=north] at (5.64,-1.0) {$t/T_{sw}$};
% Damped frame current with cancellation.
\node[text=pespurple] at (4.05,-1.7) {Frame current with cancellation};
\draw[->,black!65] (.85,-3.5)--(7.4,-3.5);
\draw[->,black!65] (.85,-3.5)--(.85,-1.95);
\node[rotate=90] at (-.12,-2.7) {$i_{\mathrm{frame}}/I_{\mathrm{pk}}$};
\foreach \val in {-1,0,1}{
 \draw (.85,-2.7+.65*\val)--(.92,-2.7+.65*\val);
 \node[anchor=east] at (.78,-2.7+.65*\val) {$\val$};
}
\draw[densely dotted,black!25] (.95,-2.7)--(7.2,-2.7);
\foreach \x/\lab in {.95/0,4.075/1,7.2/2}{
 \draw (\x,-3.5)--(\x,-3.43);
 \node[anchor=north] at (\x,-3.53) {$\lab$};
}
\node[anchor=north] at (4.075,-3.9) {$t/T_{sw}$};
''')
for values,col,style in [(i,'pespurple','')]:
 pts=[(.95+3.125*x,-2.7+.65*v) for x,v in zip(t[::4],values[::4])]
 parts.append('\\draw['+col+',line width=.75pt'+style+'] '+'--'.join(f'({x:.4f},{y:.4f})' for x,y in pts)+';\n')
parts.append('\\end{tikzpicture}\n')
(d/'fig_cm_cancellation_waveforms.tex').write_text(''.join(parts),encoding='utf-8')
f=p/'Sections/Section_VI_CommonMode.tex';s=f.read_text();a=s.index('\\caption{',s.index('\\input{Figures/Section-CommonMode/fig_cm_cancellation_waveforms}'));b=s.index('\\label{fig:spb_cm_cancellation}',a)
s=s[:a]+r'''\caption{Nonideal two-cell common-mode cancellation over two switching
periods. Small transition misalignment produces narrow residuals in
$v_{\Sigma}$ ($t_d/T_{sw}=0.003$, $t_r/T_{sw}=0.004$). Their polarities
follow the three rising and three falling cell-voltage transitions;
unequal $dv/dt$ can also produce residuals. The lower plot shows damped
frame current with cancellation, normalized to its own peak $I_{\mathrm{pk}}$.
For equal winding-to-frame capacitances $C_g$ and a shared frame-to-ground
return impedance $R_g+sL_g$,
$I_{\mathrm{frame}}(s)/V_{\Sigma}(s)=sC_g/(1+2R_gC_gs+2L_gC_gs^2)$.
The illustrative resonance has $f_0/f_{sw}=65$ and damping ratio
$\zeta=0.22$. Each residual excites alternating-polarity current ringing.
This lumped-model illustration excludes shaft charging and bearing-film
breakdown; it is not a bearing-discharge prediction.}
'''+s[b:];f.write_text(s)
print('Damped RLC frame current generated; zero mean and passive dissipation verified.')
