from pathlib import Path
import numpy as np
p=Path(__file__).resolve().parents[2];d=p/'Figures/Section-CommonMode'
# Finite raised-cosine transitions prevent unphysical impulses.
t=np.linspace(0,2,40001);tr=.004;td=.003
edges=np.array([.12,.27,.45,.55,.73,.88]);steps=np.array([1,1,1,-1,-1,-1])/3
edges=np.concatenate([edges,edges+1]);steps=np.tile(steps,2)

def waveform(delay):
 v=np.zeros_like(t);dv=np.zeros_like(t)
 for edge,step in zip(edges,steps):
  x=(t-edge-delay)/tr
  v+=step*np.where(x<=0,0,np.where(x>=1,1,(1-np.cos(np.pi*np.clip(x,0,1)))/2))
  dv+=step*np.where((x>0)&(x<1),np.pi/(2*tr)*np.sin(np.pi*np.clip(x,0,1)),0)
 return v,dv
v1,dv1=waveform(0);q2,dq2=waveform(td);v2=2-q2;vs=v1+v2;i=tr*(dv1-dq2)
# Save a regenerable generator, not just hand-drawn spikes.
head=r'''% Finite-rise complementary switching with td/Tsw=.003, tr/Tsw=.004.
% Generated by generate_cm_nonideal.py; voltage waveforms only.
\begin{tikzpicture}[font=\pesfigfont,>=latex,
 box/.style={draw=black!65,align=center,text width=2.6cm,minimum height=.9cm,inner sep=3pt}]
\node[box,fill=pesred!6] (b) at (1.2,3.6)
 {Cell 2\\[2pt]$3V_c/2-u(t)+\Delta v(t)$};
\node[box,fill=pesblue!6] (a) at (1.2,1.8)
 {Cell 1\\[2pt]$V_c/2+u(t)$};
\node[box,fill=pesgreen!6] (c) at (1.2,0)
 {\textcolor{pesgreen}{$v_{\Sigma}=2V_c+\Delta v(t)$}};
\draw[->] (a.south)--(c.north);
\draw[->] (b.west)--++(-.17,0)|-(c.west);
\foreach \y/\lo/\mid/\hi/\k in {3.6/1/1.5/2/2,1.8/0/0.5/1/1}{
 \draw[->,black!65] (4,\y-.58)--(7.4,\y-.58);
 \draw[->,black!65] (4,\y-.58)--(4,\y+.65);
 \foreach \dy/\lab in {-.45/\lo,0/\mid,.45/\hi}{
  \draw (4,\y+\dy)--(4.06,\y+\dy);
  \node[anchor=east] at (3.94,\y+\dy) {$\lab$};
 }
 \node[rotate=90] at (2.98,\y) {$v_{\mathrm{cm},\k}^{\mathrm{abs}}/V_c$};
 \draw[densely dotted,black!25] (4.08,\y)--(7.2,\y);
}
\draw[->,black!65] (4,-.65)--(7.4,-.65);
\draw[->,pesgreen] (4,-.65)--(4,.66);

\node[rotate=90,pesgreen] at (2.98,0) {$v_{\Sigma}/V_c$};

\foreach \dy/\v/\i in {-.45/1.5/-0.5,0/2/0,.45/2.5/0.5}{
 \draw[pesgreen] (4,\dy)--(4.06,\dy);
 \node[anchor=east,pesgreen] at (3.94,\dy) {$\v$};


}
\draw[densely dotted,black!25] (4.08,0)--(7.2,0);
'''
def compact_points(values):
 # Remove only collinear points (flat segments); retain resolved pulse edges.
 keep=np.r_[True,np.abs(np.diff(values,2))>1e-12,True]
 return t[keep],values[keep]
parts=[head]
for values,mid,row,col,style in [(v2,1.5,3.6,'pesred',''),(v1,.5,1.8,'pesblue',''),(vs,2,0,'pesgreen','')]:
 pts=[(4.08+1.56*x,row+.9*(v-mid)) for x,v in zip(*compact_points(values))]
 parts.append('\\draw['+col+',line width=.75pt'+style+'] '+'--'.join(f'({x:.4f},{y:.4f})' for x,y in pts)+';\n')
parts.append(r'''\foreach \x/\lab in {4.08/0,5.64/1,7.2/2}{
 \draw (\x,-.65)--(\x,-.58);
 \node[anchor=north] at (\x,-.67) {$\lab$};
}
\node[anchor=north] at (5.64,-1.0) {$t/T_{sw}$};
''')
parts.append('\\end{tikzpicture}\n')
(d/'fig_cm_cancellation_waveforms.tex').write_text(''.join(parts),encoding='utf-8')
print('Voltage-only Fig. 11 regenerated; run Figures/Exported/export_figures.py to refresh the embeddable asset.')
